//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRideSharing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CarOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarOwner()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Id { get; set; }

        
        [Display(Name = "شماره پلاک")]
        [Required(ErrorMessage = "وارد کردن شماره پلاک الزامی است")]
        [StringLength(9, ErrorMessage = "کد ملی باید 10 کاراکتری باشد", MinimumLength = 9)]
        [RegularExpression(@"^[0-9]{2}[آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهی][0-9]{3}\-[0-9]{2}$", ErrorMessage = "پلاک ماشین را با فرمت زیر وارد کنید: 11-123ب22")]
        public string CarPlate { get; set; }

        [Required(ErrorMessage = "این فیلد باید پر شود")]
        [Display(Name = "مدل ماشین")]
        [StringLength(32)]
        public string CarName { get; set; }


        [Required(ErrorMessage = "این فیلد باید پر شود")]
        [Display(Name = "رنگ ماشین")]
        [StringLength(32)]
        public string CarColor { get; set; }


        [Display(Name = "سال تولید به شمسی")]
        [Required(ErrorMessage = "مثال 89")]
        [StringLength(2, ErrorMessage = "سال تولید", MinimumLength = 2)]
        public string CarProdYear { get; set; }


        [Display(Name = "شماره گواهینامه")]
        [Required(ErrorMessage = "این فیلد حتما باید پر شود")]
        [StringLength(10, ErrorMessage = "این فیلد 10 کاراکتری است", MinimumLength = 10)]
        public string LicenseNumber { get; set; }


        [Display(Name = "توضیحات")]
        public string Description { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
