//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRideSharing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int Id { get; set; }
        public int CarOwnerId { get; set; }
        public int UserId { get; set; }


        //[StringLength(1, ErrorMessage = "از 1 تا 5 یک عدد صحیح وارد کنید", MinimumLength = 1)]
        //[Display(Name = "امتیاز")]
        //[Required(ErrorMessage = "وارد کردن امتیاز الزامی است")]
        public int Rate { get; set; }
    
        public virtual CarOwner CarOwner { get; set; }
    }
}
