//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRideSharing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CarOwners = new HashSet<CarOwner>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Seats = new HashSet<Seat>();
        }


        public int Id { get; set; }

        [StringLength(8, ErrorMessage = "شماره دانشجویی باید 8 کاراکتری باشد", MinimumLength = 8)]
        [Display(Name = "شماره دانشجویی")]
        [Required(ErrorMessage = "وارد کردن شماره دانشجویی الزامی است")]
        public string StudentId { get; set; }

        [StringLength(10, ErrorMessage = "کد ملی باید 10 کاراکتری باشد", MinimumLength = 10)]
        [Display(Name = "کد ملی")]
        [Required(ErrorMessage = "وارد کردن کد ملی الزامی است")]
        public string NationalId { get; set; }

        [Required(ErrorMessage = "این فیلد باید پر شود")]
        [Display(Name = "نام")]
        [StringLength(32)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "این فیلد باید پر شود")]
        [Display(Name = "نام خانوادگی")]
        [StringLength(32)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "وارد کردن ایمیل الزامی است")]
        [EmailAddress(ErrorMessage = "ایمیل درست وارد کنید")]
        [StringLength(32)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "ایمیل")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "شماره موبایل")]
        [Required(ErrorMessage = "وارد کردن شماره موبایل الزامی است")]
        [StringLength(11)]
        [RegularExpression(@"^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{7}$", ErrorMessage = "شماره موبایل خود را با فرمت زیر وارد کنید: 09127404062")]
        public string Phone { get; set; }


        [Display(Name = "جنسیت")]
        public int Gender { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarOwner> CarOwners { get; set; }
        public virtual Gender Gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
